#!/usr/bin/env ruby

require './environment'

@logger.info('Garrison Agent - AWS RDS - check_backup_retention')

THRESHOLD = ENV['GARRISON_RDS_THRESHOLD'] || 7

def no_backup_rds(region)
  rds = Aws::RDS::Client.new(region: region)
  response = rds.describe_db_instances
  response.db_instances.select { |i| i.backup_retention_period < THRESHOLD.to_i }

rescue Aws::RDS::Errors::OptInRequired => e
  @logger.warn "#{region} - #{e.message}"
  return []
rescue Aws::RDS::Errors::InvalidClientTokenId => e
  @logger.warn "#{region} - #{e.message}"
  return []
end

REGIONS.each do |region|
  @logger.info "Checking region #{region}"
  no_backups = no_backup_rds(region)

  no_backups.each do |instance|
    @logger.info "Raising alert for '#{instance.db_instance_identifier}'"
    alert = Garrison::Api::Alert.new
    alert.type = ENV['GARRISON_ALERT_TYPE'] || 'compliance'
    alert.family = ENV['GARRISON_ALERT_FAMILY'] || 'infrastructure'
    alert.source = 'aws-rds'

    alert.name = 'Backup Violation'
    alert.target = instance.db_instance_identifier
    alert.detail = "backup_retention_period: #{instance.backup_retention_period}"
    alert.severity = ENV['GARRISON_ALERT_SEVERITY'] || 'high'

    alert.finding = instance.to_h.to_json
    alert.finding_id = "aws-rds-#{alert.target}-backup_retention"
    alert.detected_at = Time.now.utc

    alert.urls = [
      {
        name: 'AWS Dashboard',
        url: "https://console.aws.amazon.com/rds/home?region=#{region}#dbinstance:id=#{instance.db_instance_identifier}"
      }
    ]

    alert.key_values = [
      {
        key: 'datacenter',
        value: 'aws'
      },
      {
        key: 'region',
        value: region
      },
      {
        key: 'service',
        value: 'rds'
      }
    ]

    alert.save
  end
end
